# Generated by Django 2.2.2 on 2019-06-11 02:21
import json

from django.db import migrations


# We're going to modify this example snippit with
# mineral data, then open and iterate over the json
# file and save it

def load_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Mineral = apps.get_model('minerals', 'Mineral')

    with open('assets/data/minerals.json') as source_data:
        minerals = json.load(source_data)

        for mineral in minerals:
            Mineral.objects.create(
                name=mineral.get('name', ''),
                image_filename=mineral.get('image_filename', ''),
                image_caption=mineral.get('image_caption', ''),
                category=mineral.get('category', ''),
                formula=mineral.get('formula', ''),
                strunz_classification=mineral.get('strunz_classification', ''),
                color=mineral.get('color', ''),
                crystal_system=mineral.get('crystal_system', ''),
                unit_cell=mineral.get('unit_cell', ''),
                crystal_symmetry=mineral.get('crystal_symmetry', ''),
                cleavage=mineral.get('cleavage', ''),
                mohs_scale_hardness=mineral.get('mohs_scale_hardness', ''),
                luster=mineral.get('luster', ''),
                streak=mineral.get('streak', ''),
                diaphaneity=mineral.get('diaphaneity', ''),
                optical_properties=mineral.get('namoptical_propertiese', ''),
                refractive_index=mineral.get('refractive_index', ''),
                crystal_habit=mineral.get('crystal_habit', ''),
                specific_gravity=mineral.get('specific_gravity', ''),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
